name: apphormi
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase: ^9.0.3
  firebase_core: 2.24.2
  cloud_firestore: ^2.5.1
  flare_flutter: ^3.0.0
  table_calendar: ^3.0.0
  provider: ^6.1.1
  firebase_auth: ^4.5.0
  http: ^0.13.3
  image_picker: ^0.8.0
  firebase_storage: ^11.6.0
  pdf: ^3.10.7
  csv: ^5.1.1
  path_provider: ^2.1.2
  shared_preferences: ^2.0.8
  flutter_local_notifications: ^8.2.0
  fl_chart: ^0.65.0
  charts_flutter: ^0.12.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
